# Generated by Django 5.1.1 on 2024-10-22 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cat_name',
            new_name='category_name',
        ),
    ]
