# Generated by Django 5.1.1 on 2024-10-22 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_app', '0002_rename_cat_name_product_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_name',
            new_name='cat_name',
        ),
    ]
