# Generated by Django 5.1.1 on 2024-10-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_app', '0003_rename_category_name_product_cat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreport',
            name='date',
            field=models.DateField(),
        ),
    ]
