# Generated by Django 5.1.1 on 2024-11-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_app', '0004_alter_salesreport_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100)),
            ],
        ),
    ]
