# Generated by Django 5.1.1 on 2024-11-08 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_app', '0005_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='serial_number',
            field=models.IntegerField(default=0),
        ),
    ]
