# Generated by Django 5.1.1 on 2024-11-08 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_app', '0006_category_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='serial_number',
            field=models.IntegerField(default=1),
        ),
    ]
