# Generated by Django 5.1.1 on 2024-11-08 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_app', '0007_alter_category_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='serial_number',
            field=models.IntegerField(),
        ),
    ]
