# Generated by Django 5.1.1 on 2024-11-08 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_app', '0009_product_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='serial_number',
            field=models.IntegerField(),
        ),
    ]
