# Generated by Django 5.1.1 on 2024-11-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_app', '0010_alter_product_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='labours',
            name='serial_number',
            field=models.IntegerField(default=0),
        ),
    ]
