# Generated by Django 5.1.1 on 2024-11-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_app', '0011_labours_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labours',
            name='serial_number',
            field=models.IntegerField(),
        ),
    ]
