# Generated by Django 5.1.1 on 2024-11-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_app', '0012_alter_labours_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreport',
            name='serial_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='suppliers',
            name='serial_number',
            field=models.IntegerField(default=0),
        ),
    ]
