# Generated by Django 5.1.1 on 2024-11-14 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_app', '0014_alter_salesreport_serial_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='serial_number',
        ),
        migrations.RemoveField(
            model_name='labours',
            name='serial_number',
        ),
        migrations.RemoveField(
            model_name='product',
            name='serial_number',
        ),
        migrations.RemoveField(
            model_name='salesreport',
            name='serial_number',
        ),
        migrations.RemoveField(
            model_name='suppliers',
            name='serial_number',
        ),
    ]
